langage: java
jdk: oraclejdk-15
addons:
  sonarcloud:
    organization: "damienlevy"
        token:
          secure: $SONAR_TOKEN # encrypted value of your token

    script:
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_deploy:
  - echo "done deploying"